# it is suggested that these be encrypted with ansible-vault:
# # ansible-vault edit group_vars/windows.yml

ansible_user: Administrator
#ansible_password: KEwDAdch6!m
ansible_password: ab!t0werP@55
ansible_port: 5986
ansible_connection: winrm
# # The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

ansible_winrm_transport: plaintext
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 120
ansible_winrm_read_timeout_sec: 180