---
- name: create scap-tools on remote targets - on CentOS_7.X
  file:
    path: "{{ centRemoteScapDirectoryTools }}"
    state: directory
#    mode: 0755

- name: transfert scap tools on remote targets - on CentOS_7.X
  copy:
    src: cent7-scap-tools/
    dest: "{{ centRemoteScapDirectoryTools }}cent7-scap-tools"
#    directory_mode: True
#    force: yes

- name: make sure some packages are installed on CentOS_7.X
  yum:
    name: "{{ item }}"
#    name: "{{ centRemoteScapDirectoryTools }}cent7-scap-tools/{{ item }}"
  with_items:
    - curl
    - libselinux-python

- name: installing OpenSCAP packages on CentOS_7.X
  yum:
    name: "{{ centRemoteScapDirectoryTools }}cent7-scap-tools/{{ item }}"
  with_items:
    - openscap-scanner-1.2.10-3.el7_3.x86_64.rpm
    - scap-workbench-1.1.2-1.el7.x86_64.rpm
    # - openscap-scanner
    # - scap-workbench

- name: create directory to store results & reports - on CentOS_7.X
  file:
    path: "{{ centRemoteScapDirectory }}"
    state: directory
    mode: 0755