---
# tasks file for roles/cent-prerequisites
 
- name: scap prerequisites on centos 6.X
  include: cent6-prerequisites.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
#    - ansible_os_family == "CentOS"

# - name: scap prerequisites on centos 7.X
#   include: cent7-prerequisites.yml
#   when:
#     - ansible_distribution == "CentOS"  
#     - ansible_distribution_major_version == "7"
#     - ansible_os_family == "CentOS"

- name: create directory to store results & reports
  file:
    path: "{{ centRemoteScapDirectory }}"
    state: directory
    mode: 0755