---

- hosts: tag_airbus_ansiblemanagement_Target_RedHat
  user: ec2-user
  roles:
    - rhel-prerequisites

    - os-assesment-rhel

    - setTimeZone

- hosts: tag_airbus_ansiblemanagement_Target_CentOS
  user: centos
  roles:
    - cent-prerequisites

    - setTimeZone

# - hosts: tag_airbus_ansiblemanagement_Target_RedHat
#   user: ec2-user
#   roles:
#     - rhel-prerequisites
#     - rhel7-stig-server-scan

#     - rhel6-prerequisites
#     - rhel6-stig-server-scan

#     - setTimeZone

# - hosts: tag_airbus_ansiblemanagement_Target_CentOS
#   user: centos
#   roles:
#     - cent-prerequisites

#     - cent6-prerequisites

#     - setTimeZone