- hosts: windows
  user: Administrator
  roles:
    - Win_setTimeZone
    - win_common
#     - rhel7-stig-server-scan
# #    - rhel7-stig-server-remediate
#     - setTimeZone

# - name: test
#   hosts: centos
#   user: centos
#   roles:
#     - { role: cent7-security-patch, when: executionHour is defined and executionDay is defined and executionTimezone is defined and executionHour == ansible_date_time.hour and executionDay == ansible_date_time.weekday and executionTimezone == ansible_date_time.tz}

# - name: test
#   hosts: centos
#   user: centos
#   roles:
#     - { role: cent7-security-patch, when: executionHour is defined and executionDay is defined and executionHour == ansible_date_time.hour and executionDay == ansible_date_time.weekday}
