- name: transfert NON TAILORING profiles to remote hosts
  copy:
    src: "{{ rhPathToGetCustomProfiles }}{{ rhStigServerProfile }}"
    dest: "{{ rhRemoteScapDirectory }}{{ rhStigServerProfile }}"
    mode: "u=rw,g=r,o=r"

- name: transfert TAILORING profiles to remote hosts
  copy:
    src: "{{ rhPathToGetCustomProfiles }}{{ rhStigServerTailoringProfile }}"
    dest: "{{ rhRemoteScapDirectory }}{{ rhStigServerTailoringProfile }}"
    mode: "u=rw,g=r,o=r"

- name: Get Information SCAP Content from STIG SERVER profile
  command: oscap info {{ rhRemoteScapDirectory }}{{ rhStigServerProfile }}
  register: result

- name: Displaying Lists of profiles from STIG SERVER profile
  debug:
    var: result.stdout_lines

- name: SCAN The system to evaluate STIG SERVER TAILORING Profile
  command: oscap xccdf eval --profile {{ rhStigServerTailoringProfileId }} --results-arf {{ rhRemoteScapDirectory }}{{ rhStigServerTailoringProfileScanResultName }} --report {{ rhRemoteScapDirectory }}{{ rhStigServerTailoringProfileScanReportName }} --tailoring-file {{ rhRemoteScapDirectory }}{{ rhStigServerTailoringProfile }} {{ rhRemoteScapDirectory }}{{ rhStigServerProfile }}
  register: output
  ignore_errors: yes

- name: Displaying scanning output
  debug:
    var: output.stdout_lines

- name: tranfert report to Ansible Host
  fetch:
    src: "{{ rhRemoteScapDirectory }}{{ rhStigServerTailoringProfileScanReportName }}"
    dest: "{{ rhPathToStoreResults }}{{ rhStigServerTailoringProfileScanReportName }}"

- name: tranfert results to Ansible Host
  fetch:
    src: "{{ rhRemoteScapDirectory }}{{ rhStigServerTailoringProfileScanResultName }}"
    dest: "{{ rhPathToStoreResults }}{{ rhStigServerTailoringProfileScanResultName }}"