- hosts: tag_airbus_ansiblemanagement_Target_CentOS
  user: centos
  roles:
    - setTimeZone

- name: security update
  hosts: tag_airbus_ansiblemanagement_Target_CentOS
  user: centos
  roles:
    - { role: cent7-security-patch, when: executionHour is defined and executionDay is defined and executionHour == ansible_date_time.hour and executionDay == ansible_date_time.weekday }

# - name: test
#   hosts: tag_airbus_ansiblemanagement_Target_CentOS
#   user: centos
#   roles:
#     - { role: cent7-security-patch, when: executionHour is defined and executionDay is defined and executionTimezone is defined and executionHour == ansible_date_time.hour and executionDay == ansible_date_time.weekday and executionTimezone == ansible_date_time.tz }