# - hosts: tag_airbus_ansiblemanagement_Target_CentOS
#   user: centos
#   roles:
#     - cent7-security-patch


- name: test
  hosts: tag_airbus_ansiblemanagement_Target_CentOS
  user: centos
  roles:
    - { role: cent7-security-patch, when: executionHour is defined and executionDay is defined and executionHour == ansible_date_time.hour and executionDay == ansible_date_time.weekday }
