# master playbook

#- hosts: redhat #si ne marche pas, tester airbus_ansiblemanagement_Target_RedHat au lieu de tag_airbus_ansiblemanagement_Target_RedHat
  #user: ec2-user
  #roles:
    #- rhel-prerequisites
    #- rhel7-stig-server-remediate
#
#- hosts: centos #si ne marche pas, tester airbus_ansiblemanagement_Target_CentOS au lieu de tag_airbus_ansiblemanagement_Target_CentOS
  #user: centos
  #roles:
    #- cent-prerequisites
    #- cent7-stig-server-remediate
#
#- hosts: centos
  #user: centos
  #roles:
    #- cent7-security-patch
#
#- hosts: redhat
  #user: ec2-user
  #roles:
    #- rhel7-security-patch