- name: installing OpenSCAP packages
  yum:
    name: "{{ item }}"
  with_items:
    - openscap-scanner
    - scap-security-guide
    - scap-workbench

- name: create directory to store results & reports
  file:
    path: "{{ centRemoteScapDirectory }}"
    state: directory
    mode: 0755