---
# tasks file for roles/rhel-prerequisites

- name: scap prerequisites on redhat 6.X
  include: rhel6-prerequisites.yml
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
#    - ansible_os_family == "6"

- name: scap prerequisites on redhat 7.X
  include: rhel7-prerequisites.yml
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"
#    - ansible_os_family == "RedHat"

- name: create directory to store results & reports
  file:
    path: "{{ rhRemoteScapDirectory }}"
    state: directory
    mode: 0755