- name: transfert NON TAILORING profiles to remote hosts
  copy:
    src: "{{ rhPathToGetCustomProfiles }}{{ rhStigServerProfile }}"
    dest: "{{ centRemoteScapDirectory }}{{ rhStigServerProfile }}"
    mode: "u=rw,g=r,o=r"

- name: transfert TAILORING profiles to remote hosts
  copy:
    src: "{{ rhPathToGetCustomProfiles }}{{ rhStigServerTailoringProfile }}"
    dest: "{{ centRemoteScapDirectory }}{{ rhStigServerTailoringProfile }}"
    mode: "u=rw,g=r,o=r"

- name: Get Information SCAP Content from STIG SERVER profile
  command: oscap info {{ centRemoteScapDirectory }}{{ rhStigServerProfile }}
  register: result

- name: Displaying Lists of profiles from STIG SERVER profile
  debug:
    var: result.stdout_lines

- name: SCAN The system to evaluate STIG SERVER TAILORING Profile
  command: oscap xccdf eval --profile {{ rhStigServerTailoringProfileId }} --results-arf {{ centRemoteScapDirectory }}{{ centStigServerTailoringProfileScanResultName }} --report {{ centRemoteScapDirectory }}{{ centStigServerTailoringProfileScanReportName }} --tailoring-file {{ centRemoteScapDirectory }}{{ rhStigServerTailoringProfile }} {{ centRemoteScapDirectory }}{{ rhStigServerProfile }}
  register: output
  ignore_errors: yes

- name: Displaying scanning output
  debug:
    var: output.stdout_lines

# - name: tranfert report to Ansible Host
#   fetch:
#     src: "{{ centRemoteScapDirectory }}{{ centStigServerTailoringProfileScanReportName }}"
#     dest: "{{ rhPathToStoreResults }}{{ centStigServerTailoringProfileScanReportName }}"

# - name: tranfert results to Ansible Host
#   fetch:
#     src: "{{ centRemoteScapDirectory }}{{ centStigServerTailoringProfileScanResultName }}"
#     dest: "{{ rhPathToStoreResults }}{{ centStigServerTailoringProfileScanResultName }}"