---
# tasks file for os-assesment-rhel

- name: evalute redhat 6.X
  include: rhel6-X-stig-server-scan.yml
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
#    - ansible_os_family == "6"

- name: evalute redhat 7.X
  include: rhel7-X-stig-server-scan.yml
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"
#    - ansible_os_family == "RedHat"